[package]
name = "app_events"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono.workspace = true
rabbit_mq_bus = { workspace = true }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
uuid.workspace = true

