[services.catalog-api]
http = "http://localhost:5222"
version = "2.0"

[services.basket-api]
http = "http://localhost:5221"

[services.ordering-api]
http = "http://localhost:5224"
version = "1.0"

[identity]
authority = "http://localhost:5223"
client_id = "webapprsa3"
client_secret = "secret"
callback_url = "http://localhost:3030"

[ai.openai]
chat_model = "google/gemma-4-e4b"
api_key = "not-needed"
provider_url = "http://192.168.1.140:11234/v1"

[eventbus]
url = "amqp://guest:QJWtmBP0hc1g9av6P28F4d@localhost:57251"
subscription_client_name = "webapprsa3"
retry_count = 10

[otel]
#exporter_otlp_endpoint = "http://localhost:16119"
service_name = "webapprsa3"
